#!/bin/bash

echo "🔍 GitHub 访问权限检查"
echo "======================"
echo ""

echo "请确认以下信息："
echo ""
echo "1️⃣  仓库是否真的创建了？"
echo "   请访问：https://github.com/776488326/club-selection-agent"
echo "   如果显示 404 Not Found，说明仓库不存在"
echo ""
echo "2️⃣  仓库是 Public 还是 Private？"
echo "   - 如果是 Private，你需要是仓库的所有者或有访问权限"
echo "   - 如果是 Public，任何人都可以访问"
echo ""
echo "3️⃣  Token 是否有正确的权限？"
echo "   请访问：https://github.com/settings/tokens"
echo "   找到你创建的 Token，确认它有以下权限："
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ workflow (Update GitHub Action workflows)"
echo ""
echo "4️⃣  仓库的所有者是谁？"
echo "   请确认 776488326 是你的 GitHub 用户名"
echo ""
echo "======================"
echo ""
echo "如果以上都确认无误，请尝试以下解决方案："
echo ""
echo "方案 A：重新创建仓库（推荐）"
echo "1. 访问 https://github.com/new"
echo "2. Repository name: club-selection-agent"
echo "3. Description: 校园社团选课智能体"
echo "4. 选择 Public（推荐）"
echo "5. 不要勾选任何初始化选项"
echo "6. 点击 Create repository"
echo ""
echo "方案 B：使用 SSH 方式"
echo "1. 在 GitHub 添加 SSH 密钥"
echo "2. 使用 SSH URL: git@github.com:776488326/club-selection-agent.git"
echo ""
echo "方案 C：检查 Token"
echo "1. 删除旧的 Token"
echo "2. 创建新的 Token，确保有 repo 权限"
echo "3. 重新推送"
echo ""
